import Head from 'next/head'
import Navbar from '../components/Navbar'
import Header from '../components/Header'
import UserProfile from '../components/UserProfile'
import Repositories from '../components/Repositories'
import { useState } from 'react'

export default function Home() {
  
  const [searchValue, setSearchValue] = useState()
  const [user, setUser] = useState()


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header searchValue={searchValue} setSearchValue={setSearchValue} user={user}  setUser={setUser} />
      <Navbar user={user} />
      <UserProfile user={user}  />
      <Repositories user={user}  />

    </div>
  )
}
