import Head from 'next/head'
import Navbar from '../components/Navbar'
import Header from '../components/Header'
import UserProfile from '../components/UserProfile'
import Repositories from '../components/Repositories'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Navbar/>

      <div className='grid grid-cols-3 max-w-6xl w-full h-full absolute '>
        <UserProfile/>
        <Repositories/>
      </div>

    </div>
  )
}
